export const PREDICT_BIOMASS_REQUEST = "PREDICT_BIOMASS_REQUEST";
export const PREDICT_BIOMASS_SUCCESS = "PREDICT_BIOMASS_SUCCESS";
export const PREDICT_BIOMASS_FAIL = "PREDICT_BIOMASS_FAIL";
export const PREDCIT_BIOMASS_RESET = "PREDICT_BIOMASS_RESET"
